# config/packages/security.yml
security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
        #Symfony\Component\Security\Core\User\User: plaintext
    #providers:
     #   in_memory:
      #      memory:
       #         users:
        #            user:  { password: user, roles: [ 'ROLE_USER' ] }
         #           admin: { password: admin, roles: [ 'ROLE_ADMIN' ] }
    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /
    access_control:
        - { path: ^/activite, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/localisation, roles: [ROLE_ADMIN, ROLE_USER] }